baseURL = "http://example.org/"
languageCode = "en-us"
title = "–ú–æ–π —Å–∞–π—Ç –Ω–∞ —Ö—å—é–≥–æ"
theme = "hugo-swift-theme"

[menu]
  [[menu.main]]
    name = "–ö–æ–Ω—Ç–∞–∫—Ç—ã"
    url = "about/"
    weight = 2
  [[menu.main]]
    name = "–†–∞–∑—Ä–∞–±–æ—Ç–∫–∞"
    url = "/development/"
    weight = 3
  [[menu.main]]
    name = "–ó–∞–¥–∞–Ω–∏—è"
    url = "/ispo/"
    weight = 4
  [[menu.main]]
    name = "–ì–∞–ª–µ—Ä–µ—è"
    url = "/media/"
    weight = 5

author = "–û–¥–µ–≥–æ–≤–∞ –ê–Ω–≥–µ–ª–∏–Ω–∞"
copyright = "Copyright ¬© 2020 –∑128/1."
canonifyurls = true
paginate = 4


  [[params.authors]]
    name = "–õ–∏–Ω–∞" # if fullName üëáüèª isn't set, name will be displayed on author card
    fullName = "–û–¥–µ–≥–æ–≤–∞ –ê–Ω–≥–µ–ª–∏–Ω–∞" # optional. If set, it will display on author card
    bio = "It's time to flex. Write a short or not-so-short summary about yourself."
    photo = "myPhotoFile.jpg"
    url = "https://myURLofChoice.domain"